[package]
org = "wso2"
name = "list_all_users"
version = "0.1.0" 

[build-options]
observabilityIncluded = true

# [[dependency]]
# org = "ballerinax"
# name = "notion"
# version = "2.0.0"
# repository = "local"
